export const EXECUTION_STATUS = Object.freeze({
    DRAFTED: 'DRAFTED',
    PENDING_CONFIRMATION: 'PENDING_CONFIRMATION',
    EXECUTING: 'EXECUTING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
    EXPIRED: 'EXPIRED'
});

export const CONFIRMATION_STATUS = Object.freeze({
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    REJECTED: 'REJECTED',
    BYPASSED: 'BYPASSED'
});
